-- ============================================================
-- One-off: drop draft_pages.current_page_version_id (and the copy trash_pages
-- carried so a restore could put it back).
--
-- NOT auto-applied. wrangler's migrations_dir is `migrations/`, which it does
-- not walk recursively, so nothing in here runs on `wrangler d1 migrations
-- apply`. Run it by hand, once, against each database that was created before
-- the column left the baseline:
--
--   wrangler d1 execute cms --remote --file migrations/manual/0001_drop_current_page_version_id.sql
--
-- Fresh installs need nothing: `src/core/schema.sql` and
-- `src/features/trash/schema.sql` no longer declare the column, so
-- `migrations/0001_initial_schema.sql` never creates it.
--
-- Why this is not a tracked migration
-- -----------------------------------
-- A tracked file has to be correct on a fresh install too, and neither form is:
--
--   * `ALTER TABLE ... DROP COLUMN` aborts with "no such column" on a database
--     whose baseline never created it.
--   * The table rebuild that would be correct on both (create/copy/drop/rename)
--     cannot be done safely here. D1 runs with `foreign_keys=1` and
--     `PRAGMA defer_foreign_keys` delays constraint *checks*, not `ON DELETE
--     CASCADE` actions — so `DROP TABLE draft_pages` cascades into
--     page_versions, draft_page_tags, and any child page row. Verified against
--     a seeded copy of the old schema: every version row and tag link was
--     deleted, along with the child page.
--
-- Skipping this entirely is also safe. The column is nullable, carries no
-- index or foreign key, and no code reads or writes it any more — leaving it
-- in place costs nothing but tidiness.
--
-- Both statements are in-place metadata edits; they do not rewrite rows and do
-- not touch page_versions or draft_page_tags.
-- ============================================================

ALTER TABLE draft_pages DROP COLUMN current_page_version_id;

-- Only present when the `trash` feature is enabled. Skip this statement (or
-- ignore its "no such table" error) on a profile with `trash: false`.
ALTER TABLE trash_pages DROP COLUMN current_page_version_id;
